"""Add GP checklist tables

Revision ID: 278a581769c5
Revises: 6b352c4c533b
Create Date: 2025-08-14 19:46:31.042350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '278a581769c5'
down_revision = '6b352c4c533b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gp_checklist_execucoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('operador', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gp_checklist_execucoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gp_checklist_execucoes_serial'), ['serial'], unique=False)

    op.create_table('gp_checklist_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelo', name='uq_gp_checklist_template_modelo')
    )
    op.create_table('gp_checklist_exec_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exec_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tempo_estimado_seg', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('elapsed_seg', sa.Integer(), nullable=True),
    sa.Column('ncrs', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['exec_id'], ['gp_checklist_execucoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gp_checklist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tempo_seg', sa.Integer(), nullable=False),
    sa.Column('ncr_tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['gp_checklist_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serials_created_at'))
        batch_op.drop_index(batch_op.f('ix_serials_modelo'))
        batch_op.drop_index(batch_op.f('ix_serials_montagem_id'))
        batch_op.drop_index(batch_op.f('ix_serials_numero_serie'))
        batch_op.drop_index(batch_op.f('ix_serials_status'))

    op.drop_table('serials')
    with op.batch_alter_table('seriais_maquina', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seriais_maquina_numero_serie'))

    op.drop_table('seriais_maquina')
    with op.batch_alter_table('serial_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serial_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_serial_events_kind'))
        batch_op.drop_index(batch_op.f('ix_serial_events_serial_id'))

    op.drop_table('serial_events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serial_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('serial_id', sa.INTEGER(), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=30), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['serial_id'], ['serials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serial_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serial_events_serial_id'), ['serial_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serial_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_serial_events_created_at'), ['created_at'], unique=False)

    op.create_table('seriais_maquina',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('codigo_conjunto', sa.VARCHAR(length=50), nullable=False),
    sa.Column('numero_serie', sa.VARCHAR(length=32), nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=100), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seriais_maquina', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seriais_maquina_numero_serie'), ['numero_serie'], unique=1)

    op.create_table('serials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('montagem_id', sa.INTEGER(), nullable=True),
    sa.Column('modelo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('numero_serie', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('printed_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serials_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_serials_numero_serie'), ['numero_serie'], unique=1)
        batch_op.create_index(batch_op.f('ix_serials_montagem_id'), ['montagem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serials_modelo'), ['modelo'], unique=False)
        batch_op.create_index(batch_op.f('ix_serials_created_at'), ['created_at'], unique=False)

    op.drop_table('gp_checklist_items')
    op.drop_table('gp_checklist_exec_items')
    op.drop_table('gp_checklist_templates')
    with op.batch_alter_table('gp_checklist_execucoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gp_checklist_execucoes_serial'))

    op.drop_table('gp_checklist_execucoes')
    # ### end Alembic commands ###
