"""create gp_rop_alerts

Revision ID: 40139d04be4b
Revises: 278a581769c5
Create Date: 2025-08-22 16:37:24.568197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40139d04be4b'
down_revision = '278a581769c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gp_rop_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('in_alert', sa.Boolean(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('peca_id')
    )
    with op.batch_alter_table('gp_bench_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_queue_serial_bench'))

    op.drop_table('gp_bench_queue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gp_bench_queue',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('serial', sa.TEXT(), nullable=False),
    sa.Column('modelo', sa.TEXT(), nullable=False),
    sa.Column('bench', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'waiting'"), nullable=False),
    sa.Column('source', sa.TEXT(), server_default=sa.text("'montagem'"), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gp_bench_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_queue_serial_bench'), ['serial', 'bench'], unique=1)

    op.drop_table('gp_rop_alerts')
    # ### end Alembic commands ###
