"""montagens + reprint logs

Revision ID: 6b352c4c533b
Revises: 6dbefa88f33d
Create Date: 2025-08-12 18:49:35.970296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b352c4c533b'
down_revision = '6dbefa88f33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('montagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=32), nullable=False),
    sa.Column('serial', sa.String(length=32), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('usuario', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('cancel_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_by', sa.String(length=64), nullable=True),
    sa.Column('label_printed', sa.Boolean(), nullable=False),
    sa.Column('label_printed_at', sa.DateTime(), nullable=True),
    sa.Column('label_printed_by', sa.String(length=64), nullable=True),
    sa.Column('label_print_count', sa.Integer(), nullable=False),
    sa.Column('qrcode_path', sa.String(length=255), nullable=True),
    sa.Column('label_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('montagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_montagens_serial'), ['serial'], unique=True)

    op.create_table('label_reprint_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montagem_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('reprint_by', sa.String(length=64), nullable=False),
    sa.Column('reprint_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['montagem_id'], ['montagens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('label_reprint_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_label_reprint_logs_montagem_id'), ['montagem_id'], unique=False)

    #op.drop_table('fornecedores_peca')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores_peca',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('peca_id', sa.INTEGER(), nullable=True),
    sa.Column('fornecedor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('etapa', sa.VARCHAR(length=100), nullable=True),
    sa.Column('preco', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('label_reprint_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_label_reprint_logs_montagem_id'))

    op.drop_table('label_reprint_logs')
    with op.batch_alter_table('montagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_montagens_serial'))

    op.drop_table('montagens')
    # ### end Alembic commands ###
