"""expand password_hash to 255

Revision ID: 3cf93bffeffe
Revises: afbad526ba33
Create Date: 2026-03-06 16:10:36.872768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf93bffeffe'
down_revision = 'afbad526ba33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column(
            'password_hash',
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=255),
            existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column(
            'password_hash',
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False
        )

    # ### end Alembic commands ###