"""create seriais_maquina

Revision ID: 6dbefa88f33d
Revises: 
Create Date: 2025-08-11 16:17:58.117981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbefa88f33d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seriais_maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('codigo_conjunto', sa.String(length=50), nullable=False),
    sa.Column('numero_serie', sa.String(length=32), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seriais_maquina', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seriais_maquina_numero_serie'), ['numero_serie'], unique=True)

    #op.drop_table('fornecedores_peca')
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('seriais_maquina', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seriais_maquina_numero_serie'))

    op.drop_table('seriais_maquina')


    op.drop_table('seriais_maquina')
    # ### end Alembic commands ###
